// Top-level build file where you can add configuration options common to all sub-projects/modules.
def majorVersion = 2
def minorVersion = 0
def patchVersion = 0
def buildNumber = 0
def buildVersionCode
def buildVersionName
buildVersionCode = majorVersion * 10000000 + minorVersion * 100000 + patchVersion * 100 + buildNumber
buildVersionName = "${majorVersion}.${minorVersion}.${patchVersion}"

buildscript {
    ext.kotlin_version = '1.9.25'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath 'com.google.gms:google-services:4.4.2'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
ext {
    applicationId = "org.dvbviewer.controller"
    compileSdkVersion = project.compileSdkVersion.toInteger()
    minSdkVersion = project.minSdkVersion.toInteger()
    targetSdkVersion = project.targetSdkVersion.toInteger()
    versionCode = buildVersionCode
    versionName = buildVersionName
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
